"""Extract built-in track definitions from the original Top Speed C# catalog into js/data-tracks.js.

Usage: python3 tools/extract_tracks.py <path to top_speed_net/TopSpeed.Shared/Data/Tracks/Catalog> <out.js>
"""
import json
import re
import sys

cat_dir, out = sys.argv[1], sys.argv[2]
data = open(f"{cat_dir}/Data.cs", encoding="utf-8").read()
catalog = open(f"{cat_dir}/Catalog.cs", encoding="utf-8").read()

arrays = {}
for m in re.finditer(r"TrackDefinition\[\]\s+(\w+)\s*=\s*\{(.*?)\};", data, re.S):
    segs = []
    for d in re.finditer(r"new TrackDefinition\(TrackType\.(\w+),\s*TrackSurface\.(\w+),\s*TrackNoise\.(\w+),\s*([\d.]+)f", m.group(2)):
        segs.append([d.group(1), d.group(2), d.group(3), float(d.group(4))])
    arrays[m.group(1)] = segs

tracks = {}
for m in re.finditer(r'\["(\w+)"\]\s*=\s*BuiltInTrack\(TrackWeather\.(\w+),\s*TrackAmbience\.(\w+),\s*(\w+)!?\)', catalog):
    key, weather, ambience, arr = m.groups()
    tracks[key] = {"weather": weather, "ambience": ambience, "segments": arrays[arr]}

with open(out, "w", encoding="utf-8") as f:
    f.write("// Generated by tools/extract_tracks.py from the original Top Speed track catalog. Do not edit.\n")
    f.write("export const TRACK_DATA = ")
    json.dump(tracks, f, separators=(",", ":"))
    f.write(";\n")
print(len(tracks), "tracks;", sum(len(t["segments"]) for t in tracks.values()), "segments")
